import type { CSSProperties } from "react";
import { HockeyData, HockeyGroup, hockeyPoints } from "@/lib/hockey";
function Updated({ at }: { at: string | null }) { return at ? <p className="footnote">Updated {new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit", timeZone: "Europe/Kyiv" }).format(new Date(at))} Kyiv · refreshes every two hours.</p> : null; }
export function HockeyGames({ data }: { data: HockeyData }) {
 return <section className="daily-grid" aria-label="KHL games yesterday, today and tomorrow">{data.days.map((day, index) => <section key={day.date} className={`day-column ${index === 1 ? "today" : ""}`}><div className="day-heading"><h3>{["Yesterday", "Today", "Tomorrow"][index]}</h3><time dateTime={day.date}>{new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "long", timeZone: "UTC" }).format(new Date(`${day.date}T12:00:00Z`))}</time></div><div className="day-league"><h4><a href="/hockey">KHL</a></h4>{day.unavailable ? <p className="day-empty">Games are temporarily unavailable.</p> : day.matches.length ? [...day.matches].sort((a,b)=>a.date.localeCompare(b.date)).map(game=><article className="hockey-match" key={game.id}><div className="hockey-match-meta"><time dateTime={game.date}>{new Intl.DateTimeFormat("en-GB", { hour: "2-digit", minute: "2-digit", timeZone: "Europe/Kyiv" }).format(new Date(game.date))}</time><span>{game.state.description}</span></div><div className="hockey-match-teams"><span>{game.homeTeam.name}<br/>{game.awayTeam.name}</span><strong>{game.state.score.current ?? "—"}</strong></div></article>) : <p className="day-empty">No games scheduled.</p>}</div><Updated at={day.updatedAt}/></section>)}</section>;
}
export function HockeyTable({ group, limit }: { group: HockeyGroup; limit?: number }) {
 return <div className="standings-preview"><h3>{group.name}</h3><div className={limit ? "table-wrap" : "table-wrap full-standings"} tabIndex={0} aria-label={`${group.name} standings`}><table style={{ "--stat-count": 7 } as CSSProperties}><colgroup><col className="standings-position"/><col className="standings-club"/>{Array.from({ length: 7 }, (_, i)=><col className="standings-stat" key={i}/>)}</colgroup><caption className="sr-only">{group.name}{limit ? ` top ${limit}` : " standings"}</caption><thead><tr>{["Pos","Team","P","W","OTW","OTL","L","GF–GA","Pts"].map(label=><th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{[...group.standings].sort((a,b)=>a.position-b.position).slice(0,limit).map(r=><tr key={r.team.id}><td>{r.position}</td><th scope="row">{r.team.name}</th><td>{r.gamesPlayed}</td><td>{r.wins}</td><td>{r.winsOvertime}</td><td>{r.losesOvertime}</td><td>{r.loses}</td><td>{r.scoredGoals}–{r.receivedGoals}</td><td className="points">{hockeyPoints(r)}</td></tr>)}</tbody></table></div></div>;
}
export function HockeyStandings({ data, preview = false, divisions = false }: { data: HockeyData; preview?: boolean; divisions?: boolean }) {
 const groups = data.standings.groups.filter(g=>divisions ? !/conference/i.test(g.name) : /conference/i.test(g.name));
 return <><section className="summary-grid" aria-label={divisions ? "KHL division standings" : "KHL conference standings"}>{groups.map(group=><article className="summary-card" key={group.name}>{preview && <div className="card-heading"><h2>KHL</h2><a href="/hockey">Full hockey page →</a></div>}<HockeyTable group={group} limit={preview ? 8 : undefined}/></article>)}</section>{!groups.length && <p className="empty">Standings are temporarily unavailable.</p>}<Updated at={data.standings.updatedAt}/></>;
}
